### PR TITLE
Add support for Python 3.5.

### PR DESCRIPTION
**Pull request by willrogers**
This is a bit tongue-in-cheek.

But don't you want to be supporting python 3?

### CODE REVIEW

**Comment by thomascobb** [comment]
I quite like the idea of supporting python 3.5, would you suggest using six or something like that, or would you roll your own compat thing?

**Comment by willrogers** [comment]
I used six, but I haven't done this on a large project.

You don't seem to have many requirements; they should all support python 3 (even cothread, but you can't use that on Travis, I find).

**Comment by GDYendell** [comment]
You may need to update landscape for python 3 checks:

https://docs.landscape.io/configuration.html#python-targets-2-3

**Comment by thomascobb** [comment]
Changes integrated in #51

**Pull request closed without merging**
