### PR TITLE
Remove rank padding on secondary and attribute datasets

### PR DESCRIPTION
**Pull request by GDYendell**
This makes it possible to plot with these datasets on the x axis. Requires [ADCore#474](https://github.com/areaDetector/ADCore/pull/474)

### CODE REVIEW

**Review by thomascobb — COMMENTED** [review]
How do we transition between old and new ADCore? Can we detect it via version number, or should we add a parameter to the HDF writer?

**Comment by GDYendell** [comment]
We could use $(P)$(R)ADCoreVersion_RBV, either on DRV or the HDF5 plugin.

If Mark would like it to be a config option then we can set the PV. Maybe that is cleaner anyway?

**Review by BenBradnick — COMMENTED** [review]
Looks good. If the ADCore PR is merged as-is then I guess all AreaDetector drivers would need updating to the new ADCore version on a beamline before deploying.

A comment in the changelog on this is needed and it would be useful for it to error if it finds an old ADCore version (in a similar way to PmacTrajectoryPart for the motion program version).

**Comment by GDYendell** [comment]
Does the version check need to go in code, or can we something like the `required_version` config that `DetectorDriverPart` uses?

**Comment by BenBradnick** [comment]
I feel like there's a verb missing there - do you mean move check_driver_version to ADCore/util.py and re-use the same logic in the HDFWriterPart, or just use it as the actual check?

I think it will need to be a separate check in the HDFWriterPart. You could be sending the arrays from the IOC running the AreaDetector driver to another IOC with the HDF5 plugin using the PVAccess plugin, and each of these may not be running against the same version of ADCore.

**Comment by GDYendell** [comment]
I have rebased on the latest. I think this is ready once ADCore 3.12 is released, so we can do the version check. The last commit will need amending when that happens.

**Pull request merged**
