### PR TITLE
Give Methods a "took" and "returned" log of the last call

### PR DESCRIPTION
**Pull request by thomascobb**
This will not be merged until the corresponding Malcolmjs changes have been made

### CODE REVIEW

**Comment by thomascobb** [comment]
Looks like scanpointgenerator needs to use OrderedDict for the tests to pass...

**Comment by GDYendell** [comment]
I think I wanted to use OrderedDict in scanpointgenerator at one point before, but we were worried about the performance hit. Why doesn't "==" work without converting to a string?

**Comment by thomascobb** [comment]
Cos it's gone via a convert to PVA structure, then over the wire, then json_encode...

**Comment by thomascobb** [comment]
This is a sign that the PVA structures are in undefined order, which will bite us at a later point if we don't fix it

**Comment by thomascobb** [comment]
The performance hit is creating an OrderedDict in Point(), to_dict is called quite rarely so should be fine

**Comment by thomascobb** [comment]
This has been merged into the malcolm4 branch as it contains minor breaking changes

**Pull request closed without merging**
