### PR TITLE
Fix/imalcolm and docs

### LINKED ISSUE #322: CONTRIBUTING.rst out of date
Now that we have moved to using pipenv by default I presume this should also be updated to reflect this change.

- Update running the tests to use Pipfile and pipenv
- Code styling to mention black, flake8 and isort (also mention mypy?)
- Update how to build docs

One thing I noticed was that it mentioned using dashes for release numbers until Python 3. Should we now swap to using periods?

### PR DESCRIPTION
**Pull request by BenBradnick**
This will hopefully bring the documentation up to date for installing, developing and using Malcolm now that we have moved to pipenv.

This should fix #322.

### CODE REVIEW

**Review by thomascobb — APPROVED** [review]

**Comment by BenBradnick** [comment]
Just one comment:

Martin noticed the following TODO left in CONTRIBUTING.RST:
```
TODO: add convenience for supplying private properties as per MotionChildPart
```
What should this be replaced with?

**Comment by thomascobb** [comment]
@gilesknap your name is on the commit that added that line, can you remember what it was about?

**Comment by gilesknap** [comment]
Sorry, I have no idea what that was, luckily it as the word convenience in it so we can remove it without forgetting anything essential I guess!
________________________________

**Comment by BenBradnick** [comment]
I think this is pretty close to the Python 3 template module now.

At some point the documentation probably wants to be restructured based on the template, but I will do that at a later date.

**Comment by thomascobb** [comment]
looks good

**Pull request merged**
